import { join } from "node:path";

export const HYOSHO_CSV_PATH = join(import.meta.dir, "../../data/Hyoshojoho_UTF-8.csv");
export const SHOKUBA_CSV_PATH = join(import.meta.dir, "../../data/Shokubajoho_UTF-8.csv");
export const OUTPUT_DIR = join(import.meta.dir, "../../docs/data");

// CSVのヘッダー名
export const HYOSHO_COL = {
  CORP_NUM: "法人番号",
  NAME: "商号または名称",
  PREF: "登記住所",
  ADDR: "所在地",
  CERT_NAME: "名称",
  CERT_DATE: "証明日",
  TARGET: "対象",
  DIVISION: "部門",
  ISSUER: "発行元",
} as const;

export const SHOKUBA_COL = {
  CORP_NUM: "法人番号",
  NAME: "商号または名称",
  PREF: "登記住所",
  AVG_SERVICE_SCOPE: "平均継続勤務年数-範囲",
  AVG_SERVICE_MALE: "平均継続勤務年数-男性",
  AVG_SERVICE_FEMALE: "平均継続勤務年数-女性",
  AVG_SERVICE_REGULAR: "正社員の平均継続勤務年数",
  AVG_AGE: "従業員の平均年齢",
  MONTHLY_OVERTIME: "月平均所定外労働時間",
  FEMALE_RATIO_SCOPE: "労働者に占める女性労働者の割合-範囲",
  FEMALE_RATIO: "労働者に占める女性労働者の割合",
  FEMALE_MANAGER_COUNT: "女性管理職人数",
  MANAGER_TOTAL_COUNT: "管理職全体人数（男女計）",
  FEMALE_OFFICER_COUNT: "女性役員人数",
  OFFICER_TOTAL_COUNT: "役員全体人数（男女計）",
  CHILDCARE_ELIGIBLE_MALE: "育児休業対象者数（男性）",
  CHILDCARE_ELIGIBLE_FEMALE: "育児休業対象者数（女性）",
  CHILDCARE_TAKEN_MALE: "育児休業取得者数（男性）",
  CHILDCARE_TAKEN_FEMALE: "育児休業取得者数（女性）",
} as const;

// 全都道府県のマッピング
export const ALL_PREFS: Record<string, string> = {
  北海道: "01",
  青森県: "02",
  岩手県: "03",
  宮城県: "04",
  秋田県: "05",
  山形県: "06",
  福島県: "07",
  茨城県: "08",
  栃木県: "09",
  群馬県: "10",
  埼玉県: "11",
  千葉県: "12",
  東京都: "13",
  神奈川県: "14",
  新潟県: "15",
  富山県: "16",
  石川県: "17",
  福井県: "18",
  山梨県: "19",
  長野県: "20",
  岐阜県: "21",
  静岡県: "22",
  愛知県: "23",
  三重県: "24",
  滋賀県: "25",
  京都府: "26",
  大阪府: "27",
  兵庫県: "28",
  奈良県: "29",
  和歌山県: "30",
  鳥取県: "31",
  島根県: "32",
  岡山県: "33",
  広島県: "34",
  山口県: "35",
  徳島県: "36",
  香川県: "37",
  愛媛県: "38",
  高知県: "39",
  福岡県: "40",
  佐賀県: "41",
  長崎県: "42",
  熊本県: "43",
  大分県: "44",
  宮崎県: "45",
  鹿児島県: "46",
  沖縄県: "47",
};
